sudo: required
language: python
services:
- docker
script: docker build -t scan-graph .
after_script: docker run -it --rm scan-graph /bin/sh -c "git checkout master; codeclimate-test-reporter
  --token $CODECLIMATE_REPO_TOKEN --debug"
